# Generated by Django 4.2.3 on 2023-07-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_App', '0002_rename_registration_client_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer_registration',
            old_name='bar_number',
            new_name='barnumber',
        ),
    ]
