# Generated by Django 4.2.3 on 2023-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_App', '0003_rename_bar_number_lawyer_registration_barnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_registration',
            name='email',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
