# Generated by Django 4.2.3 on 2023-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_App', '0004_alter_client_registration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, null=True)),
                ('email', models.CharField(max_length=15, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
