# Generated by Django 4.2.3 on 2023-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_App', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, null=True)),
                ('email', models.CharField(max_length=15, null=True)),
                ('feedback', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
