# Generated by Django 4.2.3 on 2023-07-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legal_App', '0007_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_registration',
            old_name='user',
            new_name='client',
        ),
    ]
